# Generated by Django 5.0.3 on 2024-03-20 19:19

import buku.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('kd_buku', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('judul_buku', models.CharField(max_length=32)),
                ('pengarang', models.CharField(max_length=32)),
                ('jenis_buku', models.CharField(max_length=32)),
                ('penerbit', models.CharField(max_length=32)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=buku.models.upload_to)),
            ],
        ),
    ]
