# Generated by Django 5.0.3 on 2024-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='bukuId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buku',
            name='kd_buku',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
