# Generated by Django 5.0.3 on 2024-03-27 08:43

import apis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pengarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RakBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apis.models.upload_to)),
                ('jumlah', models.IntegerField()),
                ('penerbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.penerbit')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.pengarang')),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.rakbuku')),
            ],
        ),
    ]
